#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     leftwheelA,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftwheelB,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightwheelA,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightwheelB,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     swing,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    hitch,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

	void driveforward(int motorspeed, int time)
	{

		motor(leftwheelA) = motorspeed;
		motor(leftwheelB) = motorspeed;
		motor(rightwheelA) = motorspeed;
		motor(rightwheelB) = motorspeed;

		wait1Msec(time);

		return;

	}

	void stopmotor()
	{
		motor(leftwheelA) = 0;
		motor(leftwheelB) = 0;
		motor(rightwheelA) = 0;
		motor(rightwheelB) = 0;

		return;
	}

	/*void turn( int direction, int motorspeedA, int motorspeedB)
	{
		while( heading < direction)
		{
			motor(leftwheelA) = motorspeedA;
			motor(leftwheelB) = motorspeedA;
			motor(rightwheelA) = motorspeedB;
			motor(rightwheelB) = motorspeedB;
  	  wait1Msec(10);

 	   rotSpeed = SensorValue(HTGYRO)- offset;

   	 heading = heading + rotSpeed * 0.01;
   }
 }
   */

